config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  get "/eventos" => 'events#new', :as => :new_event
  post "/eventos" => 'events#create', :as => :create_events
  get "/habitaciones/:permalink" => 'frontend#show_room' , :as => :show_room
  get "/restaurantes" => "frontend#restaurants" , as: :restaurants
  get "/merida" => "frontend#merida" , as: :merida
  get "/reservaciones" => 'reservations#new' , as: :new_reservation
  post "/reservaciones" => 'reservations#create' , as: :create_reservation
  get "/encuesta" => 'surveys#new' , as: :new_survey
  post "/encuesta" => 'surveys#create' , as: :create_survey
  post "/encuesta/validate" => 'surveys#validate' , as: :validate_survey

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :terms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :aliances do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :banners do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :rooms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :clients do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :reservations, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :events, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :surveys, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/resultados', action: :result_survey, as: :result, on: :collection
      get '/busqueda', action: :search_surveys_range_days, as: :search_surveys_range_days, on: :collection
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/models/aliance.rb
#Generado por keppler
require 'elasticsearch/model'
class Aliance < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mount_uploader :image, ImgUploader

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end

  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      image:  self.image.to_s,
      name:  self.name.to_s,
      external_link:  self.external_link.to_s,
    }.as_json
  end

end
#Aliance.import

app/controllers/aliances_controller.rb
#Generado con Keppler.
class AliancesController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_aliance, only: [:show, :edit, :update, :destroy]

  # GET /aliances
  def index
    aliances = Aliance.searching(@query).all
    @objects, @total = aliances.page(@current_page), aliances.size
    redirect_to aliances_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /aliances/1
  def show
  end

  # GET /aliances/new
  def new
    @aliance = Aliance.new
  end

  # GET /aliances/1/edit
  def edit
  end

  # POST /aliances
  def create
    @aliance = Aliance.new(aliance_params)

    if @aliance.save
      redirect_to @aliance, notice: 'Aliance was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /aliances/1
  def update
    if @aliance.update(aliance_params)
      redirect_to @aliance, notice: 'Aliance was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /aliances/1
  def destroy
    @aliance.destroy
    redirect_to aliances_url, notice: 'Aliance was successfully destroyed.'
  end

  def destroy_multiple
    Aliance.destroy redefine_ids(params[:multiple_ids])
    redirect_to aliances_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aliance
      @aliance = Aliance.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def aliance_params
      params.require(:aliance).permit(:image, :name, :external_link)
    end
end

app/helpers/aliances_helper.rb
module AliancesHelper
end

app/views/aliances/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/aliances/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to aliances_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @aliance do |f|
					.row
						= f.input :image
						= f.input :name
						= f.input :external_link

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/aliances/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Aliance
			= link_to edit_aliance_path(@aliance), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%img{src: "#{@aliance.image}", width: "100%"}
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @aliance.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.external_link")
			.display-value= @aliance.external_link


:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/aliances/_listing.html.haml
%tr{ id: "row-#{aliance.id}" }
	- if can? :destroy_multiple, Aliance
		%td.item-check{style:"width: 10%"}
			= link_to "", aliance_path(aliance), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{aliance.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{aliance.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{aliance.id}" }

		%td{style:"width: 30%; height: 10px;"}
			= link_to "", aliance_path(aliance, search: @query), remote: true, class: "show-row"
			%span
				%img{src: "#{aliance.image}", width: "20%"}
		%td{style:"width: 30%"}
			= link_to "", aliance_path(aliance, search: @query), remote: true, class: "show-row"
			%span
				= aliance.name
		%td{style:"width: 30%"}
			= link_to "", aliance_path(aliance, search: @query), remote: true, class: "show-row"
			%span
				= aliance.external_link

	%td{style:"width: 5%"}
		= link_to aliance_path(aliance), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/aliances/edit.html.haml
= title "Aliances - editar | #{@aliance.id}"
= render 'form'

app/views/aliances/index.html.haml
= title("Aliances - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_aliance_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |aliance|
				= render 'listing', aliance: aliance
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado aliances.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_aliance_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/aliances/new.html.haml
= title "Aliances - Nuevo"
= render 'form'

app/views/aliances/show.html.haml
= title "Aliances | #{@aliance.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Aliance
				= link_to aliance_path(@aliance), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Aliance
				= link_to edit_aliance_path(@aliance), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to aliances_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			%image{src: "#{@aliance.image}", width: "300px"}
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @aliance.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.external_link")
					.display-value.fs-body-1.tc-black-2= @aliance.external_link.to_s.humanize

app/views/aliances/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@aliance.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");