config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  get "/eventos" => 'events#new', :as => :new_event
  post "/eventos" => 'events#create', :as => :create_events
  get "/habitaciones/:permalink" => 'frontend#show_room' , :as => :show_room
  get "/restaurantes" => "frontend#restaurants" , as: :restaurants
  get "/merida" => "frontend#merida" , as: :merida
  get "/reservaciones" => 'reservations#new' , as: :new_reservation
  post "/reservaciones" => 'reservations#create' , as: :create_reservation
  get "/encuesta" => 'surveys#new' , as: :new_survey
  post "/encuesta" => 'surveys#create' , as: :create_survey
  post "/encuesta/validate" => 'surveys#validate' , as: :validate_survey

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :terms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :aliances do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :banners do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :rooms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :clients do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :reservations, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :events, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :surveys, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/resultados', action: :result_survey, as: :result, on: :collection
      get '/busqueda', action: :search_surveys_range_days, as: :search_surveys_range_days, on: :collection
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
	layout 'layouts/frontend/application'

  def index
  	@rooms = Room.all.shuffle[0...4]
		@aliances = Aliance.all.shuffle
		@banner = Banner.all.shuffle.first
  end

  def show_room
  	@room = Room.find_by permalink: params[:permalink]
  	@rooms = Room.all
  end

  def restaurants

  end

	def merida

	end

end

app/views/layouts/frontend/_footer.html.haml
.footer#footer
	.footer-email
		%center
			reservas@convencionhb.com
	.socials-row
		.social-icons
			.icon
				= link_to "https://www.facebook.com/convencionhb/" do
					%i.fa.fa-facebook
			.icon
				= link_to "https://twitter.com/convencionhb" do
					%i.fa.fa-twitter
			.icon
				= link_to "https://www.instagram.com/convencionhb" do
					%i.fa.fa-instagram
			.icon
				= link_to "https://www.pinterest.com/convencionhb/hotel-convenci%C3%B3n-boutique/" do
					%i.fa.fa-pinterest
			.icon
				= link_to "https://www.tripadvisor.com.ve/Hotel_Review-g316050-d7710858-Reviews-Convencion_Hotel_Boutique-Merida_Andean_Region.html" do
					%i.fa.fa-tripadvisor
	.contacts
		.row
			.col-lg-4
				= image_tag "frontend/Landing/logo-white.png", class: "contacts-brand"
				%br
				%br
			.col-lg-4
				.contacts-title
					Ubícanos
				%span Av. Aberto Carnevali. Edificio Hotel Convención Boutique.
				%span Sector Santa Ana. Vía La Hechicera. Mérida – Venezuela.
				%span Código Postal 5101.
				%span (+58 0414) 702 3988
				%span (+58 0274 ) 240 5311
				%br
				%br
			.col-lg-4
				.contacts-title
					Emails
				%span
					%b Reservas:
					reservas@convencionhb.com
				%span
					%b Eventos:
					eventos@convencionhb.com
				%span
					%b Ventas:
					ventas@convencionhb.com
				%span
					%b Operaciones:
					operaciones@convencionhb.com
				%span
					%b Administración:
					administracion@convencionhb.com
				%br
				%br

	.rights
		OPERADORA TURÍSTICA HOTEL CONVENCIÓN BOUTIQUE C.A. RIF: J-402890923 COPYRIGHT 2015
	.slice
		POWERED BY
		= link_to "http://www.slicegroup.xyz" do
			= image_tag 'frontend/slicegroup.png'

app/views/layouts/frontend/_google_analytics.html.haml
- if Rails.env.production?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-73761525-1', 'auto');
    ga('send', 'pageview');

app/views/layouts/frontend/_head.html.haml
%head
	%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
	%title= content_for?(:title) ? yield(:title) : 'Convención Hotel Boutique'
	%meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : '  '}"}
	%script{src:"https://maps.googleapis.com/maps/api/js?sensor=false"}
	%meta{:content => "#000000", :name => "theme-color"}
	%meta{:content => "#000000", :name => "msapplication-navbutton-color"}
	%meta{:content => "#000000", :name => "apple-mobile-web-app-status-bar-style"}/
	= stylesheet_link_tag 'frontend/application', media: 'all', 'data-turbolinks-track' => true

	= javascript_include_tag 'frontend/application', 'data-turbolinks-track' => true
	%link{:href => "http://fonts.googleapis.com/css?family=Oxygen:400,700", :rel => "stylesheet", :type => "text/css"}/

	= render 'layouts/frontend/google_analytics'
	= favicon_link_tag "frontend/favicon.png"
	= csrf_meta_tags
	:javascript
		WebFontConfig = {
			google: { families: [ 'Lato:400,900italic,900,700italic,400italic,700:latin' ] }
		};
		(function() {
			var wf = document.createElement('script');
			wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
				'://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
			wf.type = 'text/javascript';
			wf.async = 'true';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(wf, s);
		})();

app/views/layouts/frontend/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/frontend/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top#front-navbar{style: "height: 380px; top: -300px;"}

	#map

	%a.pull-right#location{onclick: "Map()"}
		LOCALIZACIÓN

	.container{style: "padding: 0px; "}
		.navbar-header
			%button.btn.btn-default.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
				.center-h
					.center-v
						%span.sr-only Toggle navigation
						%span.icon-bar
						%span.icon-bar
						%span.icon-bar
			.navbar-brand.pull-left
				= link_to "/" do
					= image_tag "frontend/Landing/logo.png"
		- if root_path?
			.collapse.navbar-collapse
				%ul.nav.navbar-nav.pull-right
					%li.links#link-home{ onclick: "scrollToAnchor('home')"}
						%a INICIO
					%li.links#link-about{ onclick: "scrollToAnchor('about')"}
						%a EL HOTEL
					%li.links#link-rooms{ onclick: "scrollToAnchor('rooms')"}
						%a HABITACIONES
					%li.links{class: " #{ 'current' if action_name == 'restaurants' } "}
						= link_to restaurants_path, class: "external" do
							RESTAURANTES
					%li.links#link-contacts{ onclick: "scrollToAnchor('footer')"}
						%a CONTACTO
					%li.links{class: " #{ 'current' if controller_name == 'reservations' } "}
						= link_to new_reservation_path, class: "external" do
							RESERVA
					%li.links{class: " #{ 'current' if controller_name == 'events' } "}
						= link_to new_event_path, class: "external" do
							EVENTOS
					%li.links{class: " #{ 'current' if action_name == 'merida' } "}
						= link_to merida_path, class: "external" do
							MÉRIDA
		-else
			.collapse.navbar-collapse
				%ul.nav.navbar-nav.pull-right
					%li.links
						= link_to root_path(anchor: "home"), class: "external" do
							INICIO
					%li.links
						= link_to root_path(anchor: "about"), class: "external" do
							EL HOTEL
					%li.links{class: " #{ 'current' if action_name == 'rooms' } "}
						= link_to root_path(anchor: "rooms"), class: "external" do
							HABITACIONES
					%li.links{class: " #{ 'current' if action_name == 'restaurants' } "}
						= link_to restaurants_path, class: "external" do
							RESTAURANTES
					%li.links
						= link_to root_path(anchor: "contacts"), class: "external" do
							CONTACTO
					%li.links{class: " #{ 'current' if controller_name == 'reservations' } "}
						= link_to new_reservation_path, class: "external" do
							RESERVA
					%li.links{class: " #{ 'current' if controller_name == 'events' } "}
						= link_to new_event_path, class: "external" do
							EVENTOS
					%li.links{class: " #{ 'current' if action_name == 'merida' } "}
						= link_to merida_path, class: "external" do
							MÉRIDA

app/views/layouts/frontend/application.html.haml
!!!
%html
  = render 'layouts/frontend/head'
  %body
    %header
      = render 'layouts/frontend/navigation'
    %main{:role => "main"}
      = #render 'layouts/frontend/messages'
      = yield
      = render "layouts/frontend/footer"