config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  get "/eventos" => 'events#new', :as => :new_event
  post "/eventos" => 'events#create', :as => :create_events
  get "/habitaciones/:permalink" => 'frontend#show_room' , :as => :show_room
  get "/restaurantes" => "frontend#restaurants" , as: :restaurants
  get "/merida" => "frontend#merida" , as: :merida
  get "/reservaciones" => 'reservations#new' , as: :new_reservation
  post "/reservaciones" => 'reservations#create' , as: :create_reservation
  get "/encuesta" => 'surveys#new' , as: :new_survey
  post "/encuesta" => 'surveys#create' , as: :create_survey
  post "/encuesta/validate" => 'surveys#validate' , as: :validate_survey

  scope :admin do

  	resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :terms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :aliances do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :banners do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :rooms do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :clients do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :reservations, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :events, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :surveys, except: [:new, :create] do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/resultados', action: :result_survey, as: :result, on: :collection
      get '/busqueda', action: :search_surveys_range_days, as: :search_surveys_range_days, on: :collection
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/controllers/surveys_controller.rb
#Generado con Keppler.
class SurveysController < ApplicationController
  include SurveysHelper
  before_filter :authenticate_user!, except: [:new, :create, :validate]
  layout :resolve_layout
  load_and_authorize_resource except: [:new, :create]
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  def index
    surveys = Survey.searching(@query).all
    @objects, @total = surveys.page(@current_page), surveys.size
    redirect_to surveys_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /surveys/1
  def show
    respond_to do |format|
      format.html { render action: 'show' }
      format.pdf { render pdf: 'Encuesta', template: 'surveys/show.pdf.haml', handlers: [:haml] }
      format.xlsx do
        @build_tables = build_tables
        render xlsx: 'show', filename: "Encuesta_#{@survey.id} #{@survey.created_at.strftime('%Y-%m-%d %I:%M')}.xlsx"
      end
    end
  end

  def search_surveys_range_days
    @survey = Survey.new(survey_params)
    @result1 = Survey.where(["checkin >= '#{Date.parse("#{@survey.email}")}' AND checkout <= '#{Date.parse("#{@survey.room}")}'"])
    @welcome_attention_4 = 0
    @welcome_attention_3 = 0
    @welcome_attention_2 = 0
    @welcome_attention_1 = 0

    @welcome_professionality_4 = 0
    @welcome_professionality_3 = 0
    @welcome_professionality_2 = 0
    @welcome_professionality_1 = 0

    @welcome_decoration_4 = 0
    @welcome_decoration_3 = 0
    @welcome_decoration_2 = 0
    @welcome_decoration_1 = 0

    @welcome_butler_4 = 0
    @welcome_butler_3 = 0
    @welcome_butler_2 = 0
    @welcome_butler_1 = 0

    @welcome_info_quality_4 = 0
    @welcome_info_quality_3 = 0
    @welcome_info_quality_2 = 0
    @welcome_info_quality_1 = 0

    @welcome_info_quality_4 = 0
    @welcome_info_quality_3 = 0
    @welcome_info_quality_2 = 0
    @welcome_info_quality_1 = 0

    #--- 2 parte encuesta-----

    @room_cleaning_4 = 0
    @room_cleaning_3 = 0
    @room_cleaning_2 = 0
    @room_cleaning_1 = 0

    @room_comfort_4 = 0
    @room_comfort_3 = 0
    @room_comfort_2 = 0
    @room_comfort_1 = 0

    @room_decoration_4 = 0
    @room_decoration_3 = 0
    @room_decoration_2 = 0
    @room_decoration_1 = 0

    @room_cleanliness_4 = 0
    @room_cleanliness_3 = 0
    @room_cleanliness_2 = 0
    @room_cleanliness_1 = 0

    @room_channels_4 = 0
    @room_channels_3 = 0
    @room_channels_2 = 0
    @room_channels_1 = 0

    @room_soundless_4 = 0
    @room_soundless_3 = 0
    @room_soundless_2 = 0
    @room_soundless_1 = 0

    #-- 3 parte ---- 

    @facilities_lobby_4 = 0
    @facilities_lobby_3 = 0
    @facilities_lobby_2 = 0
    @facilities_lobby_1 = 0

    #-- 4 parte ----

    @staff_professionalism_4 = 0
    @staff_professionalism_3 = 0
    @staff_professionalism_2 = 0
    @staff_professionalism_1 = 0

    @staff_simpathy_4 = 0
    @staff_simpathy_3 = 0
    @staff_simpathy_2 = 0
    @staff_simpathy_1 = 0

    @staff_speed_4 = 0
    @staff_speed_3 = 0
    @staff_speed_2 = 0
    @staff_speed_1 = 0

    @staff_effectiveness_4 = 0
    @staff_effectiveness_3 = 0
    @staff_effectiveness_2 = 0
    @staff_effectiveness_1 = 0

    @staff_availability_4 = 0
    @staff_availability_3 = 0
    @staff_availability_2 = 0
    @staff_availability_1 = 0

    @staff_cleanliness_4 = 0
    @staff_cleanliness_3 = 0
    @staff_cleanliness_2 = 0
    @staff_cleanliness_1 = 0

     #---- 5 parte ----- 
    @met_by_6 = 0
    @met_by_5 = 0
    @met_by_4 = 0
    @met_by_3 = 0
    @met_by_2 = 0
    @met_by_1 = 0


    @result1.each do |result|
      if result.welcome_attention == 4
        @welcome_attention_4 = @welcome_attention_4 + 1
      end
      if result.welcome_attention == 3
        @welcome_attention_3 = @welcome_attention_3 + 1
      end
      if result.welcome_attention == 2
        @welcome_attention_2 = @welcome_attention_2 + 1
      end
      if result.welcome_attention == 1
        @welcome_attention_1 = @welcome_attention_1 + 1
      end
      if result.welcome_professionality == 4
        @welcome_professionality_4 = @welcome_professionality_4 + 1
      end
      if result.welcome_professionality == 3
        @welcome_professionality_3 = @welcome_professionality_3 + 1
      end
      if result.welcome_professionality == 2
        @welcome_professionality_2 = @welcome_professionality_2 + 1
      end
      if result.welcome_professionality == 1
        @welcome_professionality_1 = @welcome_professionality_1 + 1
      end
      if result.welcome_decoration == 4
        @welcome_decoration_4 = @welcome_decoration_4 + 1
      end
      if result.welcome_decoration == 3
        @welcome_decoration_3 = @welcome_decoration_3 + 1
      end
      if result.welcome_decoration == 2
        @welcome_decoration_2 = @welcome_decoration_2 + 1
      end
      if result.welcome_decoration == 1
        @welcome_decoration_1 = @welcome_decoration_1 + 1
      end
      if result.welcome_butler == 4
        @welcome_butler_4 = @welcome_butler_4 + 1
      end
      if result.welcome_butler == 3
        @welcome_butler_3 = @welcome_butler_3 + 1
      end
      if result.welcome_butler == 2
        @welcome_butler_2 = @welcome_butler_2 + 1
      end
      if result.welcome_butler == 1
        @welcome_butler_1 = @welcome_butler_1 + 1
      end
      if result.welcome_info_quality == 4
        @welcome_info_quality_4 = @welcome_info_quality_4 + 1
      end
      if result.welcome_info_quality == 3
        @welcome_info_quality_3 = @welcome_info_quality_3 + 1
      end
      if result.welcome_info_quality == 2
        @welcome_info_quality_2 = @welcome_info_quality_2 + 1
      end
      if result.welcome_info_quality == 1
        @welcome_info_quality_1 = @welcome_info_quality_1 + 1
      end

      #-- 2 parte ------
      
      if result.room_cleaning == 4
        @room_cleaning_4 = @room_cleaning_4 + 1
      end
      if result.room_cleaning == 3
        @room_cleaning_3 = @room_cleaning_3 + 1
      end
      if result.room_cleaning == 2
        @room_cleaning_2 = @room_cleaning_2 + 1
      end
      if result.room_cleaning == 1
        @room_cleaning_1 = @room_cleaning_1 + 1
      end 

       if result.room_comfort == 4
        @room_comfort_4 = @room_comfort_4 + 1
      end
      if result.room_comfort == 3
        @room_comfort_3 = @room_comfort_3 + 1
      end
      if result.room_comfort == 2
        @room_comfort_2 = @room_comfort_2 + 1
      end
      if result.room_comfort == 1
        @room_comfort_1 = @room_comfort_1 + 1
      end

      if result.room_decoration == 4
        @room_decoration_4 = @room_decoration_4 + 1
      end
      if result.room_decoration == 3
        @room_decoration_3 = @room_decoration_3 + 1
      end
      if result.room_decoration == 2
        @room_decoration_2 = @room_decoration_2 + 1
      end
      if result.room_decoration == 1
        @room_decoration_1 = @room_decoration_1 + 1
      end 

      if result.room_cleanliness == 4
        @room_cleanliness_4 = @room_cleanliness_4 + 1
      end
      if result.room_cleanliness == 3
        @room_cleanliness_3 = @room_cleanliness_3 + 1
      end
      if result.room_cleanliness == 2
        @room_cleanliness_2 = @room_cleanliness_2 + 1
      end
      if result.room_cleanliness == 1
        @room_cleanliness_1 = @room_cleanliness_1 + 1
      end 

      if result.room_channels == 4
        @room_channels_4 = @room_channels_4 + 1
      end
      if result.room_channels == 3
        @room_channels_3 = @room_channels_3 + 1
      end
      if result.room_channels == 2
        @room_channels_2 = @room_channels_2 + 1
      end
      if result.room_channels == 1
        @room_channels_1 = @room_channels_1 + 1
      end

      if result.room_soundless == 4
        @room_soundless_4 = @room_soundless_4 + 1
      end
      if result.room_soundless == 3
        @room_soundless_3 = @room_soundless_3 + 1
      end
      if result.room_soundless == 2
        @room_soundless_2 = @room_soundless_2 + 1
      end
      if result.room_soundless == 1
        @room_soundless_1 = @room_soundless_1 + 1
      end

      #---- 3 parte-----

      if result.facilities_lobby == 4
        @facilities_lobby_4 = @facilities_lobby_4 + 1
      end
      if result.facilities_lobby == 3
        @facilities_lobby_3 = @facilities_lobby_3 + 1
      end
      if result.facilities_lobby == 2
        @facilities_lobby_2 = @facilities_lobby_2 + 1
      end
      if result.facilities_lobby == 1
        @facilities_lobby_1 = @facilities_lobby_1 + 1
      end

      #----- 4 parte ------  

      if result.staff_professionalism == 4
        @staff_professionalism_4 = @staff_professionalism_4 + 1
      end
      if result.staff_professionalism == 3
        @staff_professionalism_3 = @staff_professionalism_3 + 1
      end
      if result.staff_professionalism == 2
        @staff_professionalism_2 = @staff_professionalism_2 + 1
      end
      if result.staff_professionalism == 1
        @staff_professionalism_1 = @staff_professionalism_1 + 1
      end

      if result.staff_effectiveness == 4
        @staff_effectiveness_4 = @staff_effectiveness_4 + 1
      end
      if result.staff_effectiveness == 3
        @staff_effectiveness_3 = @staff_effectiveness_3 + 1
      end
      if result.staff_effectiveness == 2
        @staff_effectiveness_2 = @staff_effectiveness_2 + 1
      end
      if result.staff_effectiveness == 1
        @staff_effectiveness_1 = @staff_effectiveness_1 + 1
      end

      if result.staff_simpathy == 4
        @staff_simpathy_4 = @staff_simpathy_4 + 1
      end
      if result.staff_simpathy == 3
        @staff_simpathy_3 = @staff_simpathy_3 + 1
      end
      if result.staff_simpathy == 2
        @staff_simpathy_2 = @staff_simpathy_2 + 1
      end
      if result.staff_simpathy == 1
        @staff_simpathy_1 = @staff_simpathy_1 + 1
      end

      if result.staff_speed == 4
        @staff_speed_4 = @staff_speed_4 + 1
      end

app/helpers/surveys_helper.rb
module SurveysHelper
  def build_tables
    [
      [ 'Bienvenida', welcoming_attr ],
      [ 'Habitaciones', room_attr ],
      [ 'Instalaciones', facilities_attr ],
      [ 'Restaurant Lobby “El Encuentro Restaurant”', lobby_attr ],
      [ 'Restaurant Terraza “Les Golfes Gastrobar”', terrace_attr ],
      [ 'Personal del Hotel', staff_attr ]
    ]
  end

  def welcoming_attr
    [
      'welcome_attention', 'welcome_professionality', 'welcome_decoration',
      'welcome_butler', 'welcome_info_quality'
    ]
  end

  def room_attr
    %w(
      room_cleaning room_comfort room_decoration
      room_cleanliness room_channels room_soundless
    )
  end

  def facilities_attr
    %w(
      facilities_lobby facilities_business_center
      facilities_gym facilities_stores facilities_other
    )
  end

  def lobby_attr
    %w(
      lobby_breakfast lobby_menu lobby_waiting
      lobby_service lobby_staff lobby_quality_price
    )
  end

  def terrace_attr
    %w(
      terrace_breakfast terrace_menu terrace_waiting
      terrace_service terrace_staff terrace_quality_price
    )
  end

  def staff_attr
    %w(
      staff_professionalism staff_simpathy staff_speed
      staff_effectiveness staff_availability staff_cleanliness
    )
  end

  def important_attributes
    %w(
      welcome_attention welcome_professionality welcome_decoration
      welcome_butler welcome_info_quality room_cleaning room_comfort
      room_decoration room_cleanliness room_channels room_soundless
      facilities_lobby staff_professionalism staff_simpathy staff_speed
      staff_effectiveness staff_availability staff_cleanliness met_by
    )
  end
end

app/views/surveys/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.insert_chart.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/surveys/_errors_survey.html.haml
- unless @survey.errors[:base].empty?
	%div.alert.alert-danger.form-alert{ onclick: "hideFormAlert();" }
		%div
			Para continuar debe llenar correctamente el formulario.
			- @survey.errors[:base].each_with_index do |e,i|
				- if i <= 4
					%p{style: 'margin-bottom: 0;'}= "- #{e}"

app/views/surveys/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Survey
			= link_to edit_survey_path(@survey), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.insert_chart.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.ip")
			.display-value= @survey.ip
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @survey.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @survey.email
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.room")
			.display-value= @survey.room
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.checkin")
			.display-value= @survey.checkin
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.checkout")
			.display-value= @survey.checkout


:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/surveys/_listing.html.haml
%tr{ id: "row-#{survey.id}" }
	- if can? :destroy_multiple, Survey
		%td.item-check{style:"width: 10%"}
			= link_to "", survey_path(survey), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{survey.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{survey.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{survey.id}" }
	%td{style:"width: 30%"}
		= link_to "", survey_path(survey, search: @query), remote: true, class: "show-row"
		%span
			= survey.checkin
	%td{style:"width: 30%"}
		= link_to "", survey_path(survey, search: @query), remote: true, class: "show-row"
		%span
			= survey.checkout
	%td{style:"width: 30%"}
		= link_to "", survey_path(survey, search: @query), remote: true, class: "show-row"
		%span
			= survey.name
	%td{style:"width: 30%"}
		= link_to "", survey_path(survey, search: @query), remote: true, class: "show-row"
		%span
			%i.material-icons{ class: survey.status_color }= "sentiment_#{survey.status_icon}"
	%td{style:"width: 5%"}
		= link_to survey_path(survey), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/surveys/_personal_data.html.haml
.info
  %p
    Su valoración nos será muy útil para mejorar nuestras instalaciones y el servicio que prestamos. Por favor, dedique 5 minutos para completar esta encuesta
  %p Muchas gracias de antemano por su colaboración.

= simple_form_for @survey, url: validate_survey_path, html: {class: 'validate-survey'}, remote: true do |f|
  .title-form
    %a Información General
  %p.info-text Favor llenar los datos para poder validarlo.
  .row
    .col-lg-5.col-md-5.col-sm-12.col-xs-12
      .field
        = f.input :name, label: false, :placeholder=> "NOMBRE Y APELLIDO"

    .col-lg-5.col-md-4.col-sm-8.col-xs-12
      .field
        = f.input :email, label: false, :placeholder=> "EMAIL"

    .col-lg-2.col-md-3.col-sm-4.col-xs-12
      .field
        = f.input :room, label: false, :placeholder=> "N° HABITACIÓN"
    %br

  .form-actions
    = f.button :submit, "VALIDAR", class: "btn btn-save btn-validate", id: "btn-submit" , style: "width: auto;", controller: "surveys", action: "validate", disabled: true
    %center
      %i.fa.fa-circle-o-notch.fa-spin.fa-3x.fa-fw{style: "color: #e2001a"}

:javascript
  $( ".fa-fw" ).hide();

  $( "#btn-submit" ).click(function() {
    $( "#btn-submit").hide();
    $( ".fa-fw" ).show();
  });

app/views/surveys/_show_other_data.html.haml
%tr
  %th.category-title{ colspan: '6' } Otros datos: ¿Cómo nos ha conocido?
%tr
  %td{ colspan: '4' } Por recomendación
  %td{ colspan: '2' }
    - if survey.met_by == 1
      .i.material-icons close
%tr
  %td{ colspan: '4' } Reportaje en revista/periódico
  %td{ colspan: '2' }
    - if survey.met_by == 2
      .i.material-icons close
%tr
  %td{ colspan: '4' } Anuncio publicitario
  %td{ colspan: '2' }
    - if survey.met_by == 3
      .i.material-icons close
%tr
  %td{ colspan: '4' } Internet
  %td{ colspan: '2' }
    - if survey.met_by == 4
      .i.material-icons close
%tr
  %td{ colspan: '4' } Redes sociales
  %td{ colspan: '2' }
    - if survey.met_by == 5
      .i.material-icons close
%tr
  %td{ colspan: '4' } Agencia de viaje
  %td{ colspan: '2' }
    - if survey.met_by == 6
      .i.material-icons close
%tr
  %td.empty-td{ colspan: '6' }

app/views/surveys/_survey_fields.html.haml
- if @already_answered.try(:any?)
  .title-form.already-answered
    %a Lo sentimos, solo puede contestar una encuesta cada 24 horas.

- else
  = simple_form_for @survey, url: create_survey_path do |f|
    .title-form
      %a Información General
    .row
      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .field
          = f.input :name, label: false, :placeholder=> "NOMBRE Y APELLIDO", readonly: true

      .col-lg-6.col-md-6.col-sm-6.col-xs-12
        .field
          = f.input :email, label: false, :placeholder=> "EMAIL", readonly: true

      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .field
          = f.input :room, label: false, :placeholder=> "NUMERO DE HABITACIÓN", readonly: true

      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .field
          = f.input :checkin, as: :string, label: false, :placeholder=> "FECHA DE CHECK-IN", input_html: {class: "datepicker date_survey"}

      .col-lg-4.col-md-4.col-sm-4.col-xs-12
        .field
          = f.input :checkout, as: :string, label: false, :placeholder=> "FECHA DE CHECK-OUT", input_html: {class: "datepicker date_survey2"}

    = render 'radio_buttons', f: f, errors: @survey.errors || nil
    = render 'other_data_radio_buttons', f: f, errors: @survey.errors || nil

    .info
      %p
        %center Si tiene algún comentario adicional que no le hayamos preguntado, por favor, escríbalo aquí.
    .row
      = f.input :comment, label: false
    %br

    .form-actions
      = f.button :submit, "ENVIAR", class: "btn btn-save", id: "btn-submit" , style: "width: auto;", controller: "surveys", action: "create"

:javascript
  $('.date_survey2').datepicker({
    dayViewHeaderFormat: 'YYYY',
    format: 'yyyy-mm-dd',
    endDate: 'm',
    autoclose: 'true',
    todayBtn: 'linked',
    language: 'es'
  });

  $('.date_survey').datepicker({
    dayViewHeaderFormat: 'YYYY',
    format: 'yyyy-mm-dd',
    autoclose: 'true',
    endDate: '-1d',
    todayBtn: false,
    language: 'es'
  });

app/views/surveys/new.html.haml
= title "Convención Hotel Boutique | Nueva encuesta"
= render 'form'

app/views/surveys/show.html.haml
= title "Surveys | #{@survey.id}"
.wrapper
  .wrapper-body.container
    .actions
      - if can? :delete, Survey
        = link_to survey_path(@survey), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
          = material_icon.md_18.delete.css_class("md-dark")
      - if can? :update, Survey
        = link_to edit_survey_path(@survey), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
          = material_icon.md_18.create.css_class("md-dark")
      = link_to surveys_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
        = material_icon.md_18.arrow_back.css_class("md-dark")
      = link_to survey_path(@survey, format: 'pdf'), target: '_blank', class: "btn-floating btn-flat tooltipped right", "data-position" => "bottom", "data-tooltip" => "Descargar PDF" do
        = material_icon.md_18.picture_as_pdf.css_class("md-dark")
      = link_to survey_path(@survey, format: 'xlsx'), class: "btn-floating btn-flat tooltipped right", "data-position" => "bottom", "data-tooltip" => "Descargar xlsx" do
        = material_icon.md_18.file_download.css_class("md-dark")

    .panel-body#body-show.order-event-show
      .container
        %table.table.table-bordered
          %tr
            %th.category-title{ colspan: '6' } Datos personales
          %tr
            %th{ colspan: '3' } Nombre y Apellido
            %th{ colspan: '2' } Email
            %th{ colspan: '1' } N° Habitación
          %tr
            %td{ colspan: '3' }= @survey.name
            %td{ colspan: '2' }= @survey.email
            %td{ colspan: '1' }= @survey.room
          %tr
            %th{ colspan: '6' } Check-in / Check-out
          %tr
            %td{ colspan: '6' }= "#{@survey.checkin} / #{@survey.checkout}"
          %tr
            %td.empty-td{ colspan: '6' }

          - build_tables.each do |category|
            %tr
              %th.category-title{ colspan: '6' }= category.first
            %tr
              %th{ colspan: '2' }
              %th{ colspan: '1' } Excelente
              %th{ colspan: '1' } Bien
              %th{ colspan: '1' } Regular
              %th{ colspan: '1' } Malo
            - category.last.each do |attr|
              = render 'show_survey_row', survey: @survey, attribute: attr
            %tr
              %td.empty-td{ colspan: '6' }

          = render 'show_other_data', survey: @survey

          - unless @survey.comment.blank?
            %tr
              %th{ colspan: '6' } Comentario
            %tr
              %td{ colspan: '6' }= @survey.comment

app/views/surveys/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@survey.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");